// ABOUTME: Cross-language byte-parity tests. Loads checked-in JSON fixtures
// ABOUTME: generated by the TS reference and asserts Swift output matches within abs <= 1e-9.

import Foundation
import Testing
@testable import PerfectFreehand

/// A minimal `StrokeInputPoint` conformance used by the fixture tests.
/// Public so the parameterized tests can construct it without `@testable` gymnastics.
public struct InputPoint: StrokeInputPoint, Sendable {
    public let x: Double
    public let y: Double
    public let pressure: Double?
    public init(x: Double, y: Double, pressure: Double? = nil) {
        self.x = x
        self.y = y
        self.pressure = pressure
    }
}

@Suite("Fixtures")
struct FixtureTests {
    struct Fixture: Decodable, Sendable, CustomStringConvertible {
        let name: String
        let input: [[Double]]
        let options: FixtureOptions
        let expected: [[Double]]
        var description: String { name }
    }

    struct FixtureOptions: Decodable, Sendable {
        let size: Double
        let thinning: Double
        let smoothing: Double
        let streamline: Double
        let simulatePressure: Bool
        let start: FixtureTaper
        let end: FixtureTaper
        let last: Bool
    }

    struct FixtureTaper: Decodable, Sendable {
        let taper: Double
        let cap: Bool
    }

    /// The fixture file basenames that ship with the test bundle.
    /// Restricting to a known list keeps stray `package.json`/`tsconfig.json`/
    /// `regenerate.ts` out of the test stream even if SPM ever copies them in.
    static let fixtureNames: [String] = [
        "basic-line",
        "long-curve",
        "closed-loop",
        "single-point",
        "two-points",
        "zigzag",
        "varying-pressure",
        "no-pressure-simulate-true",
        "no-pressure-simulate-false",
        "constant-pressure",
        "streamline-0",
        "streamline-1",
        "thinning-0",
        "thinning-1",
        "taper-aggressive",
        "empty-input",
        "two-identical-points",
        "very-small-size",
    ]

    static func loadFixture(_ name: String) throws -> Fixture {
        let url = try #require(
            Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"),
            "missing fixture: \(name).json"
        )
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Fixture.self, from: data)
    }

    @Test("fixture byte-parity within abs <= 1e-9", arguments: Self.fixtureNames)
    func match(name: String) throws {
        let fixture = try Self.loadFixture(name)

        let input = fixture.input.map { coords in
            InputPoint(
                x: coords[0],
                y: coords[1],
                pressure: coords.count > 2 ? coords[2] : nil
            )
        }

        var opts = StrokeOptions()
        opts.size = fixture.options.size
        opts.thinning = fixture.options.thinning
        opts.smoothing = fixture.options.smoothing
        opts.streamline = fixture.options.streamline
        opts.simulatePressure = fixture.options.simulatePressure
        opts.start = TaperOptions(
            taper: fixture.options.start.taper == 0 ? .none : .length(fixture.options.start.taper),
            cap: fixture.options.start.cap
        )
        opts.end = TaperOptions(
            taper: fixture.options.end.taper == 0 ? .none : .length(fixture.options.end.taper),
            cap: fixture.options.end.cap
        )
        opts.last = fixture.options.last

        let actual = getStroke(points: input, options: opts)

        #expect(
            actual.count == fixture.expected.count,
            "\(fixture.name): vertex count \(actual.count) vs \(fixture.expected.count)"
        )

        let pairs = zip(actual, fixture.expected).enumerated()
        for (i, (a, e)) in pairs {
            #expect(
                Swift.abs(a.x - e[0]) <= 1e-9,
                "\(fixture.name)[\(i)].x: \(a.x) vs \(e[0]) (delta \(a.x - e[0]))"
            )
            #expect(
                Swift.abs(a.y - e[1]) <= 1e-9,
                "\(fixture.name)[\(i)].y: \(a.y) vs \(e[1]) (delta \(a.y - e[1]))"
            )
        }
    }
}
